version: '3.8'
services:
  backend:
    image: gus9300/flolink-deploy-backend:latest
    ports:
      - "8080:8080"

  frontend:
    image: gus9300/flolink-deploy-frontend:latest
    ports:
      - "80:80"
