services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flolink
      MYSQL_USER: gus9300
      MYSQL_PASSWORD: tvxq1226@
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    restart: always

  backend:
    image: gus9300/flolink-deploy-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flolink
      SPRING_DATASOURCE_USERNAME: gus9300
      SPRING_DATASOURCE_PASSWORD: tvxq1226@
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/ubuntu/flolink-deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080

volumes:
  mysql-data:
    driver: local
