services:
  mysql:
    container_name: mysql
    image: gus9300/flolink-deploy-mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flolink
      MYSQL_USER: gus9300
      MYSQL_PASSWORD: tvxq1226@
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Seoul
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
    restart: always

  backend:
    image: gus9300/flolink-deploy-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flolink
      SPRING_DATASOURCE_USERNAME: gus9300
      SPRING_DATASOURCE_PASSWORD: tvxq1226@
      TZ: Asia/Seoul
    volumes:
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mysql

  frontend:
    image: gus9300/flolink-deploy-frontend:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt/live/flolink-plus.xyz/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/flolink-plus.xyz/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /home/ubuntu/flolink-deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
      TZ: Asia/Seoul
      
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: soddong
      MINIO_ROOT_PASSWORD: tvxq1226@
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - ./data:/data
      - ./init-bucket.sh:/docker-entrypoint-initdb.d/init-bucket.sh 

volumes:
  mysql-data:
    driver: local

