name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # master 브랜치에 Push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Docker Cache
        run: docker builder prune --force

      # 1. 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 2. Backend Docker 빌드 및 Push
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-backend:latest
          context: ./backend
          file: ./backend/Dockerfile

      # 3. Frontend Docker 빌드 및 Push
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-frontend:latest
          context: ./frontend
          file: ./frontend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. 원격 서버로 배포
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            mkdir -p /home/ubuntu/flolink-deploy
            cd /home/ubuntu/flolink-deploy
            docker-compose down
            docker-compose pull
            docker-compose up -d
