name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # master 브랜치에 Push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Docker Cache
        run: docker builder prune --force

      # 1. 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정
      - uses: docker/setup-buildx-action@v3

      # 3. Docker Hub 로그인
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Inject application.yml
      #   run: |
      #     mkdir -p src/main/resources
      #     echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
      #     cat src/main/resources/application.yml

      # - name: Verify application.yml
      #   run: |
      #     if [ -f src/main/resources/application.yml ]; then
      #       echo "application.yml exists and contains:"
      #       cat src/main/resources/axpplication.yml
      #     else
      #       echo "application.yml was not created."
      #       exit 1
      #     fi
      
      # 4. Backend Docker 빌드 및 Push
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-backend:latest
          context: ./backend
          file: ./backend/Dockerfile

      # 5. Frontend Docker 빌드 및 Push
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-frontend:latest
          context: ./frontend
          file: ./frontend/Dockerfile

      - name: Build and Push MySQL Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-mysql:latest
          context: ./mysql
          file: ./mysql/Dockerfile

      - name: Deploy to Server with Updated docker-compose.yml
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            mkdir -p /home/ubuntu/flolink-deploy
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd /home/ubuntu/flolink-deploy
            docker-compose down
            docker-compose pull
            docker-compose up -d
